### ISSUE TITLE
Lande-side

### ISSUE THREAD

**Issue by ploeh** [Tobi3010/DIS-Project#14]
I stedet for at alle lister blot vises på forsiden (`Index`) synes jeg at det kunne være fint hvis man f.eks. kunne navigere til et land (`/Country/4567`) og så se de restauranter, der er i det land. Alternativt kunne den side vise en tabel over de byer, hvor man kan finde restauranter.

**Comment by Zhadowseb** [comment]
Lukkes så det ikke virker til at der er issues ved aflevering.
